# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUILogued.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 900, 900))
        self.label.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"fontcolor:rgb(0,0,0)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Tutorial = QtWidgets.QPushButton(self.centralwidget)
        self.Tutorial.setGeometry(QtCore.QRect(210, 80, 321, 51))
        self.Tutorial.setObjectName("Tutorial")
        self.Tienda = QtWidgets.QPushButton(self.centralwidget)
        self.Tienda.setGeometry(QtCore.QRect(210, 150, 321, 51))
        self.Tienda.setObjectName("Tienda")
        self.Nueva_partida = QtWidgets.QPushButton(self.centralwidget)
        self.Nueva_partida.setGeometry(QtCore.QRect(210, 220, 321, 51))
        self.Nueva_partida.setObjectName("Nueva_partida")
        self.Salir = QtWidgets.QPushButton(self.centralwidget)
        self.Salir.setGeometry(QtCore.QRect(210, 410, 321, 51))
        self.Salir.setObjectName("Salir")
        self.Editar_info = QtWidgets.QPushButton(self.centralwidget)
        self.Editar_info.setGeometry(QtCore.QRect(210, 290, 321, 51))
        self.Editar_info.setObjectName("Editar_info")
        self.Eliminarcuenta = QtWidgets.QPushButton(self.centralwidget)
        self.Eliminarcuenta.setGeometry(QtCore.QRect(210, 350, 321, 51))
        self.Eliminarcuenta.setObjectName("Eliminarcuenta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Iniciar sesion"))
        self.label_2.setText(_translate("MainWindow", "Bienvenido "))
        self.Tutorial.setText(_translate("MainWindow", "Tutorial"))
        self.Tienda.setText(_translate("MainWindow", "Tienda"))
        self.Nueva_partida.setText(_translate("MainWindow", "Nueva partida"))
        self.Salir.setText(_translate("MainWindow", "Salir"))
        self.Editar_info.setText(_translate("MainWindow", "Editar informacion"))
        self.Eliminarcuenta.setText(_translate("MainWindow", "Eliminar cuenta"))
